### ISSUE TITLE
Replace SleepWarp

### ISSUE THREAD

**Issue by octylFractal** [ILikePizza555/Ponydev-SFE-Modpack#6]
<spoiler>
<details>
<summary>Stacktrace (Mojmap)</summary>

```java
java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
        at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:84)
        at net.minecraft.world.level.levelgen.LegacyRandomSource.next(LegacyRandomSource.java:49)
        at net.minecraft.world.level.levelgen.BitRandomSource.nextFloat(BitRandomSource.java:56)
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:242)
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:213)
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:201)
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:379)
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:326)
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:333)
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:897)
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:283)
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671)
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

**Comment by octylFractal** [comment]
SleepWarp is a fundamentally broken mod. Working on a replacement.

**Comment by octylFractal** [comment]
Could maybe replace with https://github.com/octylFractal/OUTASPLE. A little wonky, needs refinement if others want it.
